
service: invoices-http-api

# serverless-webpack plugin to transpile ES6
plugins:
  - serverless-webpack
  - serverless-offline

# serverless-webpack configuration
# Enable auto-packing of external modules
custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:us-east-1:*:*"

functions:

  create:
    handler: src/create.main
    events:
      - http:
          path: invoices
          method: post
          cors: true
          authorize: aws_iam

  get:
    handler: src/get.main
    events:
      - http:
          path: invoices/{id}
          method: get
          cors: true
          authorize: aws_iam
          
  list:
    handler: src/list.main
    events:
      - http:
          path: invoices
          method: get
          cors: true
          authorize: aws_iam

  update:
    handler: src/update.main
    events:
      - http:
          path: invoices/{id}
          method: put
          cors: true
          authorize: aws_iam

  delete:
    handler: src/delete.main
    events:
      - http:
          path: invoices/{id}
          method: delete
          cors: true
          authorize: aws_iam